---
title: "Research Efforts"
format: html
---

The long-term area of focus is in the relationship between stress and arrhythmogenesis, which boils down to the relationship between *substrate*, *trigger*, and *event*. 

> "Why did he die on a Tuesday and not on a Monday?"
> ~ Douglas Zipes

In the 50 years since the advent of the coronary care unit [@Lown1968], our ability to prevent arrhythmogenesis has not made a significant difference in clinical outcomes (with a stable 1 out of 5 deaths being secondary to arrhythmia [@Hayashi2015; @Lown1977].
This topic fascinates me, and has led me to continue to explore this path, with a mixed focus between atrial and ventricular arrhythmias.

# Current projects

This serves as a summary of current/active research projects.
Weekly, [research-in-progress updates](https://asshah4.github.io/research/t32/rip.html) and general agendas from [mentorship meetings](https://asshah4.github.io/research/t32/mentors.html) are available at these links.

| | | |
| --- | --- | --- |
| MSIMI and CV Mortality | A large prospective cohort study measuring myocardial ischemia in response to mental stress, with extensive follow-up. Analytical skills included the development of recurrent event models (AG, PWP, MSM, marginal, conditional). Recurrent event software in R was developed. Middle-author Publication in JAMA | 2019-2020 |
| HRV and Myocardial Perfusion | Evaluated circadian patterns in autonomic function using 24-hour Holter data, generating HRV with a focus on spectral density analyses. Compared these patterns with CFR on quantitate PET, finding a relationship with CFR and early morning low HRV. First-author publication in IJC | 2017-2020 |
| GEH and Diabetes | Using the CARRS cohort, evaluated ECG-based patterns of GEH and diabetes, finding a strong relationship with cardiac fibrosis and widening of specific GEH parameters. WIP | 2018-2019 |
| HRV and Psychosocial Factors | Evaluated changes in HRV from baseline to several years later in the ARIC Study. Found that psychosomatic stress (in the form of vital exhaustion) led to a persistent decrease in high frequency HRV, a surrogate of vagal tone. First-author Publication in JAHA | 2016-2020 |
| AFL and Family History | Statistical analysis of relationship between early onset AFL and family history, which notably yields different phenotypes in Whites and Blacks. [WIP](https://asshah4.github.io/aflubber) | 2022 |
| Disturbances of Neurocardiac Axis | TL1 and F32 grant focused on evaluating of myocardial ischemia and changes in autonomic function using HRV. Pilot study with completed recruitment. Publication of Thesis and WIP | 2019-now | 
| Vagolysis and Arrhythmogenesis | Measurement of vagolysis in arrhythmogenesis in the electrophysiology lab and using clinical and epidemiological data. Currently working on the development/progress [towards a K23 award](https://asshah4.github.io/research/k23/planning.html), including pilot data collection. | 2022-now |

*GEH = global electrical heterogeneity; HRV = heart rate variability; CV = cardiovascular; SCD = sudden cardiac death; AFL = family history; MSIMI = mental stress induced myocardial ischemia; PET = positron emission tomography*

# Research skills

Technical research skills:

- epidemiology and biostatistics
- study design (IRB, informed consent, subjection enrollment)
- digital signal processing (HRV, ECG)
- programming in R, MATLAB
- harmonic regression
- advanced survival models with recurrent events

# Previous work

## Stress and Cardiovascular Epidemiology

_Physiological and psychological stress and cardiovascular mortality, from a neurocardiac perspective_

- Effect of autonomic reactivity and resting vagal tone in cardiovascular mortality
- Depression and dysregulation of the autonomic nervous system, published in [JAHA](https://doi.org/10.1161/JAHA.120.017172)
- Circadian variability in autonomic function and microvascular coronary disease, published in [IJC](https://doi.org/10.1016/j.ijcard.2020.01.069)
- Atrial fibrillation recurrence after catheter ablation
- Family history and genetic basis of [atrial flutter](https://asshah4.github.io/aflubber)
- Cardiovascular biorepository for computational assessment of trajectories/history

## Stress and Arrhythmognesis

_Mechanisms behind stress and arrhythmia generation (or degeneration) in a pre-clinical and clinical electrophysiology context_

- Murine models of vagolysis leading to triggered arrhythmias, which was initially proposed as an [AHA IPA](https://asshah4.github.io/research/grants/aha_innovative_project_2022.html), but then withdrawn

## Computational Neurocardiology and Biostatistics

_Programming-based approaches in signal processing and biostatistics_

- Measuring circadian patterns and disturbances using a [cosinor regression method](https://asshah4.github.io/card)

## Clinical Projects

_Work being done as a cardiology fellow at UIC/JBVA_

- Atrial fibrillation and efficacy of cardioversion
- Pulmonary embolism management with a coordinated response team (PERT)
- Endocarditis lesion characteristics in a gain-independent manner using pixel density changes
- Arrhythmia and device management in setting of endocarditis
