---
title: Mentorship Meetings
author: Anish S. Shah, MD, MS
institute:
- University of Utah
- University of Illinois Chicago
- Emory University
format: 
  revealjs:
    scrollable: true
    chalkboard: true
execute:
  cache: true
tbl-cap-location: bottom
fig-cap-location: bottom
---

# 05/22/24 | AJS

## Agenda {.smallest}

- HRV/CVD Mortality in JAMA Network Open
- CARRS paper 
- UK Biobank / MR for AF genetics (validation cohort)
- K23 approach
  1. EP-lab and pharmacological "mental stress cocktail" in PTSD
  1. Computational prediction of arrhythmias incorporating neurocardiac axis in PTSD 
  1. Genetic variants in stress response and arrhythmia risk in PTSD
- Software updates (modeling package published, EGM package + paper pending)
- AHA early career investigator award (Epi? Clinical Cardiology?)
  - AFEQT/SDOH? &rarr; manuscript drafted but pending
  - HRV/CVD paper? $rarr; however abstract already published

# 05/07/24 | AJS

## AF DAG

```{mermaid}
flowchart LR
	ecg["ECG"]
	scar["Scar"]
	comp["Computational Modeling"]
	arr["Arrhythmia Prediction"]
	eps["EPS"] 
	mri["MRI"]
	phen["Phenotypes"]
	ptsd["PTSD"] 
	ans["Autonomic Modulation"]
	geno["Genotypes"] 
	ans --> eps
	ptsd --> geno
	ecg --> geno
	scar --> ecg
	mri --> ecg
	ecg --> phen
	ecg --> geno
	geno <--> phen
	eps --> comp
	scar --> comp
	comp --> arr
	
```

# 04/17/24 | RR

## Agenda {.smaller}

1. Current/updates on research areas
	a. AFGen collaboration
	a. UIC/Emory mentors
1. K23/KL2/CDA application
	a. Mentorship network at Utah
	a. Collaborative overlap
	a. Specific aims overview

## Updates

- Expect $\ge$ 5 *first-author* publications prior to EP fellowship start (2 published, 2 in review, 1 being drafted)
- Two software publications (harmonic regression statistical package, causality-based modeing package)
- Current project on phenotyping AF based on ECG and neural networks to predict genetic variants (AFGen collaboration) $\leftarrow$ manuscript (after validation)
- Evaluating stress-associated genetic variants in WES/GWAS for future AF risk, with plans for validation via UK Biobank (Emory collaboration)

## Utah-based research

- MacLeod: work on ECG-I for arrhythmia prediction and atrial tissue characterization
- Ranjan/Dosdall: work on MRI-based prediction of arrhythmia pathways
- Tristani-Firouzi: genetics of arrhythmias, Utah Population Database

## Draft of Aims {.center}

---

__Aim 1: Identify ECG-based phenotypes of paroxysmal AF.__
We will evaluate the ECG manifestation of (A) patterns of scar based on cardiac MRI/EPS, and (B) contributions of genetic variants in sarcomeric/structural proteins and ion channelopathies that are associated with AF. 
Our [working hypothesis]{.underline} is that scar-based atrial myopathy can be identified by ECG, and can distinguish between re-entry versus focal triggers for AF.

---

__Aim 2: Determine the differences in APD heterogeneity of scar tissue in the context of modulated autonomic activity.__
Our [working hypothesis]{.underline} is that the interaction between APD heterogeneity and autonomic modulation will predict differential risk for future AF, particularly in cases of abnormal baseline autonomic activity such as PTSD.

---

__Aim 3: Identify the role of novel, rare variants for future AF risk in stress-related conditions.__
Our [working hypothesis]{.underline} is that rare variants identified in a population with abnormal stress responses will be associated wiht increased future risk of AF in a large cohort study.


# 04/16/24 | SHC

## Agenda {.smaller}

1. Review slides from AFGen *RIP* presentation
1. Extension of project
	a. Extension/continuation of project
	a. Timeline
	a. Validation
	
## Project extension {.smaller}

- Consider as part of K23 application focused on ECG-based phenotyping
- Phenotyping but focusing on *structural/sarcomeric* and *ion channel* variants
- Initial training data to be analyzed by mid-May, with intent for AHA submission
- Similar to...
	- @Wang2023
	- @Choi2021
	- @Weng2020
	- @Ntalla2020
- Validation?
	- All of Us
	- TOPMed
	- UK Biobank

## ECG Prediction of Structural and Ion Channel Mutants in AF {.smaller}

This is an expansion of the __ECG/TTN__ project, which found [ECG could feasibly provide above-chance accuracy in identify TTN LOF variants]{.underline}.
Now, expand to additional *wild-types* and *mutants*...

- Sarcomeric/structural variants (e.g. TTN, PITX2, LMNA, NUP155, GJA1/5)
- Ionic channel variants (e.g. KCNE1-5, KCNQ1, SCN5A)
- No known genetic contributors (excluding any patient with non-benign VUS in any above genes $\pm$ SNPs associated with polygenic risk for AF)
	

# 02/14/24 | EJB

## Agenda {.smaller}

1. Personal/professional updates (brief)
1. "Big hairy audacious goal"
1. AFGen fellowship/consortium, TOPMed
1. K23 location and strategy
	a. Specific aims
	a. Mentorship network
	a. Importance of "ownership" of datasets

# 02/12/24 | RR

## Agenda {.smaller}

1. Personal research status
	a. "Big picture" goal - functional prediction of arrhythmia onset
	a. Current research projects
	a. Mentorship network
1. Research overview at Utah 
	a. Research groups with overlapping interest
	a. Strategic mentorship for K23 award
	a. Timeline and expectations
	
## Big picture {.smaller}

::: {.callout-important}
Why do large, underwater mammals, with respectively __larger atria__ have low burden of atrial fibrillation? Why do arrhythmias only occur on __ascent phase of dive__?
:::

1. Plan to be with translational cardiac electrophysiologist, focusing on signal processing, molecular/genetic mechanisms, and the autonomic nervous system
1. Underlying question is how [stress can lead to arrhythmogenesis]{.underline}
1. Study how arrhythmia events are mediated by potential [inappropriate vagolytic mechanisms in atrial fibrillation]{.underline}.
1. Long-term goal is to [phenotype AF]{.underline} and develop targeted, individualized therapies (e.g. functional mapping, alternative boundary predictions in EP)

## Current projects {.smaller}

- ECG-based prediction of severity of TTN variants using deep learning (computational/genetics)
- Machine learning for annotations of EGM (computational)
- Phenotyping paroxysmal AF based on ECG and TTE criteria (epidemiology)
- Mental *stress reactivity* and CVD mortality (epidemiology)
- AFEQT and social determinants of health in minority population (epidemiology)
- "Isolated" or "premature" AFL with family history (genetics)
- Cosinor/harmonic regression software (computational)
- GWAS of abnormal *stress reactivity*

## Non-specific aims

1. Epidemiology / ECG-based aim: risk prediction, machine learning (i.e. ECG-informed arrhythmia risk scores)
1. EP-lab based aim: repolarization mapping, intra-EPS stress testing
1. Genetics-focused aim: TTN impact on AF, genetics of stress physiology (e.g. HRV)

## Research network {.smaller}

- Amit J. Shah, MD, MSCR (Emory) = cardiologist $\rightarrow$ __Rob MacLeod, PhD__
- Alvaro Alonso, MD, PhD (Emory) = epidemiologist, ARIC, atrial fibrillation
- Viola Vaccarino, MD, PhD (Emory) = epidemiologist, mental stress
- Arshed Quyyumi, MD (Emory) = cardiologist, coronary disease
- Rachel Lampert, MD (Yale) = electrophysiologist, mental stress
- Dawood Darbar, MD (UIC) = electrophysiologist, genetics, atrial fibrillation $\rightarrow$ __Martin Tristani-Firouzi, MD__
- Emelia Benjamin, MD, ScM (BU) = cardiologist, epidemiologist, atrial fibrillation, genetics (AFGen Consortium)

## Research at Utah {.smaller}

- MacLeod = signal processing for ECG/EGM data
- Ranjan = MRI and structural evaluation of atria (in AF)
- Bunch = AF and cognitive decline (area of interest of __Alvaro Alonso__ as well)
- Tristani-Firouzi = genetics of arrhythmias, Utah Population Database
- Palatinus = molecular mechanisms of current trafficking
- Guo = genetics/VUS and CVD mechanisms
- Dosdall = EGM/arrhythmia mapping, activation patterns

## Wrap-up

- Opinions and thoughts
- Questions/concerns

# References

::: {#refs}
:::
