---
title: Mentorship Meetings
author: Anish S. Shah, MD, MS
institute:
- University of Illinois at Chicago
- Emory University
format: 
  revealjs:
    scrollable: true
execute:
  cache: true
tbl-cap-location: bottom
fig-cap-location: bottom
---

# June 9 | DD {.smaller}

## End-of-year meeting

1. Research training and productivity
1. Career planning (EP fellowship)
1. Upcoming milestones and research plans
1. Formative feedback

## Research training

:::: {.columns}
::: {.column width="50%"}
[Completed training]{.underline}:

- Signal processing coursework through *MIT OpenCourseWare* in Aug 2022 to Dec 2022
- NLP coursework through *Stanford Online* in Feb 2023 to May 2023
:::
::: {.column width="50%"}
[In process]{.underline}:

- Computational Genomics series through *Harvard Bioinformatics* May 2023 to present
:::
::::

## Research products {.smaller}

:::: {.columns}
::: {.column width="50%"}
[First Author]{.underline}:

- AF/AFL Manuscript = ~~JAMA Cardiology~~ *JACC EP*
- HRV/CVD Manuscript = ~~Circulation~~ *EHJ*
- LSPro/WFDB Abstract = *HRx 2023*
- HRV/CVD Abstract = *ACC 2023*
- LSPro/WFDB Software = *CRAN* [^1] 

:::
::: {.column width="50%"}
[Middle Author]{.underline}:

- Abstracts: ACC 2023 x 3, HRS 2023 x 1, AHA 2023 x 2
- Manuscripts:
	- HRV & Incident Heart Failure *WIP*
	- AF Recurrence & Race *WIP*

[Article Reviewer]{.underline}:

- IJC x 1, AHJ x 1, Heart x 1
:::
::::

[^1]: Peer-reviewed software repository

## Career planning

[Applying to EP fellowship]{.underline}:

a. LOR: (1) Darbar/Amit (combined letter), (2) Yeshwant (clinical), (3) Avitall (clinical), (4) Auseon (program director)
a. Locations: NW, UIC, UofC, Loyola, UPenn, Vermont (Spektor), UCLA (Shivkumar), VCU (Ellenbogen), JHU

::: aside
Fellowship location will likely determine long-term K23 application
:::

## Paper proposal {.smaller}

Project to evaluate ECG-correlates of genetic variants with paroxysmal AF directly, similar to @Verweij2020 approach. Basis of **AFGEN fellowship** application.

[Exposure]{.underline}: common and rare genetic variants

[Outcome]{.underline}:

1. ECG parameters during sinus (300 individuals x 4-10 ECGs x avg 10 beats = 20k to 35k ECG volume)
2. dominant frequency and coarseness of F waves during AF

[Hypothesis]{.underline}: *Genetic variants in genes associated with paroxysmal AF, including novel variants, will have significant association with P wave abnormalities*

::: aside
Genetic variants = 

- cardiomyopathy genes (TTN, NPPA, TBX5, MYL4, TTN, LMNA)
- arrhythmia genes (KCNQ1, SCN5A, SCN10A, EXT1)
- cardiovagal genes (NPY2R, GALR1)
:::

## Upcoming milestones {.smaller}

1. Committee meeting = June 2023 (confirm milestones with Darbar/Amit/Auseon)
1. Echocardiography boards = July 2023
1. AFGEN application = July 2023
1. Attend 3 conferences this year (ACC, HRS, and R::conf), with associated abstract submissions = 2023 to 2024
1. Complete ECG analyses by August 2023, genetic analyses by September 2023, and submit manuscript on ECG/genetic in AF by October 2023
1. General cardiology boards = October 2023
1. Match into (top-tier) EP fellowship = December 2023

# April 28 | DD 

## {.smaller}

:::: {.columns}
::: {.column width="50%"}
- Preliminary data for AIMS
	- NLP/phenotyping needs coursework and mentorship with Boyd
	- ML/DSP needs significant engineering/programming time
- AF phenotyping to identify those with heavier percentage of "triggers" versus those with higher burden of "substrate"
- EGM assessment of AF, evaluating scar-burden, conduction velocity, with underlying theory of "wavelet re-entry" as a boundary problem

:::
::: {.column width="50%"}
- [x] AFL/FH manuscript to JAMA Cardiology
- [x] HRV/CVD manuscript to co-authors
- [ ] HRV/CVD manuscript to European Heart Journal
- [ ] AF/CA outcomes statistical review
- [ ] Analysis of CCTS data pull
- [ ] [MUSE ECG data in XML format]{.orange}
- [ ] IRB for EP lab research
:::
::::

# April 11 | AJS 

## {.smaller}

:::: {.columns}
::: {.column width="50%"}
- Submitting paper to JAMA cardiology on AFL/FH 
- Completed revised concordance and AUC on HRV/CVD paper
- WFDB for EGM, initialized I/O
- NLP/ontology planning started
:::
::: {.column width="50%"}
- [ ] Analyses for non-first author paper on AF/ablation outcomes
- [ ] [HRV/CVD paper thoughts on concordance and NRI]{.orange}
- [ ] [Specific aims review]{.orange}
- [ ] Final committee decisions: Darbar, Shah, Alvaro, Boyd, Lampert?
- [ ]	Ontology of "stress"?
:::
::::

# March 31, 2023 | DD 

## {.smaller}

:::: {.columns}
::: {.column width="50%"}
HRV/CVD: Finalizing paper draft, to submit EHJ

CAR: Adjudicated ECGs, designed data collection, [pending analyses]{.orange}

AFL/FH:

- [x] Paper draft, second round
- [ ] [Identify all authors]{.orange}
- [ ] Finalize JAMA cardiology submission
:::

::: {.column width="50%"}
Phenotyping AF:

- [ ] eMERGE PRS and PhenotypeKB
- [x] AWS HPC access 
- [x] CCTS DRA for data pull
- [ ] Ablation database 
:::
::::

## {.smaller}

:::: {.columns}
::: {.column width="50%"}
K23:

- [x] Draft of aims
- [ ] [Feedback on aims]{.orange}
- [ ] Prelim data on AF phenotypes
- [ ] Prelim data in the EP lab

Mentorship:

- [x] Identified majority of mentorship committee = Darbar, Shah, Alonso, _Boyd_ (advisor), _Lampert_ 
- [x] Meeting with McCauley (3/3)
- [x] Meeting with Boyd (3/16)
- [ ] [Genetics mentor, local or at another institution?]{.orange} &rarr; _will need more genetics training_
:::
::: {.column width="50%"}
Training:

- [x] DSP training &rarr; coursework
- [ ] [NLP training &rarr; coursework]{.orange}
- [ ] [Computational training in genetics]{.orange}

Career:

- [ ] [Delineate timeline and strategy for EP fellowship]{.orange}
- [ ] Identify potential institutions and letters of support/introduction
:::
::::

# March 3, 2023 | DD 

## {.smaller}

:::: {.columns}
::: {.column width="50%"}
HRV/CVD:

- [x] Non-linearity evaluated, analyses being repeated
- [x] Identify appropriate level journal (EHJ)
- [ ] Presenting to Amit MS-EP group

AFL/FH:

- [x] Paper draft has been drafted
- [ ] [Genetic analyses]{.orange}
- [ ] [Identify all authors]{.orange}
- [ ] Send in JAMA Cardiology format
:::
::: {.column width="50%"}
CAR:

- [x] Adjudicated ECG and designed data collection pattern
- [ ] [Role and next steps]{.orange}
- [ ] REDCap inconsistencies noted &rarr; responsibility?
:::
::::

## {.smaller}

:::: {.columns}
::: {.column width="50%"}
K23:

- [x] [Draft of aims]{.orange}
- [ ] [Feedback on aims]{.orange}
- [ ] Which areas require prelim data?

Mentorship:

- [x] Identified majority of mentorship committee = Darbar, Shah, Alonso, _McCauley_, _Boyd_, _Lampert_
- [ ] Meeting with McCauley (3/3)
- [ ] Meeting with Boyd (3/16)
- [ ] [Genetics mentor, local or at another institution?]{.orange}
:::
::: {.column width="50%"}
Training:

- [ ] Computational training in signal processing
- [ ] [Computational training in genetics]{.orange}

Career:

- [ ] [Delineate timeline and strategy for EP fellowship]{.orange}
:::
::::

# References

::: {#refs}
