---
title: Phenotyping AF
subtitle: Project Page
author: Anish S. Shah, MD|MS
format: 
  pdf:
    geometry:
      - left=0.5in
      - right=0.5in
tbl-cap-location: bottom
fig-cap-location: bottom
---

# Background

Paroxysmal AF contains a broad spectrum of disease, regardless of burden, frequency, hemodynamic or vascular complications, or etiology.
Several attempts have been made at pursuing more salient models, however they combine both paroxysmal and persistent AF into a binary diagnosis.
Two recent studies have documented 4 potential clusters may exist [@Pastori2020; @Vitolo2021]:

1.  Younger, lower comorbidities
1.  High CV risk factors
1.  High CV comorbidities
1.  High rates of non-CV comorbidities (e.g. cancer)

@Wineinger2019 showed that in terms of duration and episodes of AF, there may be a *staccato* (short, frequent episodes) versus *legato* (long, infrequent) patterns to AF, however unknown about underlying clinical relevance.

In this proposal, I aim to phenotype paroxysmal AF into clinically-relevant subtypes. This serves as the basis for future work for evaluating differences in prognosis (including endocardial mapping patterns to recurrence).

## Hypothesis

[Hypothesis]{.underline}: *Diagnoses of paroxysmal AF will segregate into clusters based on electrical, clinical, and structural cardiac properties.*

The overall approach will be to use high-dimensionality reduction techniques to create finite clusters that alllow for segregation based on mutliple vector-spaces. 
This approach also allows for future *multi-state modeling* and *survival* techniques based on "events" &rarr; ablation, cardioversion, medication intensification, changes in burden, cardiomyopathy, etc.

# Data

## Data sources

The data that is currently available to answer this is derived from three sources:

a. UIC Multi-Ethnic AF Registry: ~1800 patients with various classes of AF that have contributed blood sampling for genetic analysis
b. Clinical Data Warehouse: collected by the CCTS, houses Cerner and EPIC charts from 2010 onwards, including clinical notes, procedure notes, diagnoses, vitals, medications
c. MUSE: ECGs from ~2000s to today with full digital/raw signal (10 seconds x 8 leads)

## Key variables

The key variables that will be used are a combination of clinical, electrical, imaging that will allow for creation of multiple dimensions for analysis.

:::: {.columns}
::: {.column width="34%"}

**Electrocardiography**

[Sinus]{.underline}

- P-wave indices: voltage, AUC, duration, dispersion, terminal forces
- Global parameters: PR interval, P/R amplitude ratio
- Rate: high-frequency HRV, HR
 
[AF]{.underline}

- Conduction properties: ventricular response, shortest/longest RR intervals 
- Atrial parameters: dominant frequency (Fourier multi-transform), F-wave relative voltage + ∆ voltage over time

:::
::: {.column width="33%"}

**Clinical**

- Age, Sex, Race
- Weight + ∆ weight over time
- Comorbidities (HTN, DM, HLD, CHF, CAD)
- CHADS2VAS2C score
- ADHF and h/o CHF
- Anti-arrhythmic intensification (AAD, BB uptitration, cardioversion, ablation)
- Atrial arrhythmias + recurrence + burden of AF over time
- Blood pressure + ∆ over time
- HR and responsiveness of HR over time

:::
::: {.column width="33%"}

**Echocardiography**

- Volumes: LA, RA, LV, LVIDD
- Pressures: RVSP, PA pressures
- Diastology: E/e' ratio, A wave duration/velocity, A wave reversal
- Function: LVEF, RVEF, LA strain

:::
::::

# Methods and approach

There are four components of this work that will eventually come-together for analysis.

a. Electrocardiography-based rhythm and morphology evaluation: capitalizes on arrhythmia-focused research while utilizing signal processing and ML-based clustering approaches
a. Echocardiography and structural imaging assessments of cardiac function: low-level NLP in structured data parsing
a. Clinical context including co-morbidities, vitals, medications, procedures: epidemiology-focused contextualization of patient attributes/trajectories
a. Changes in parameters with time: survival analyses and recurrent event analyses (multi-state models)

The initial focus will be on ECG-based signal processing approaches. This will involve downloading/extracting MUSE data in an XML format, converting the binary data into digital, and finally converting to the WFDB format (Waveform Database Software Package). Then, the WFDB binary files can be annotated for QRS location, beat segmentation, P-wave evaluation, etc. Using ML approaches, can subsequently convert and derive intervals, identify/confirm rhythm, and generate related parameters such as vector gradients. This will be used to generate features both in AF and in sinus rhythm. Using cluster-based approaches, can then identify if patterns emerge in ECG subtypes of paroxysmal AF.

# Timeline

```{mermaid}
%%| fig-responsive: true
%%| fig-width: 6
%%| fig-height:	6 
gantt
	dateFormat MM/YYYY
	axisFormat %b-%Y
	excludes weekends
	section Intake
		MUSE ECG to XML									:done, muse, 05/2023, 07/2023
		XML ECG to WFDB 								:done, wfdb, 04/2023, 90d
		Cluster hosting of data					:done, acer, 06/2023, 60d
		Import CCTS data								:ccts, 05/2023, 90d
	section Data tidying
		Sinus rhythm parameters 				:nsr, 07/2023, 30d
		AF rhythm parameters 		 				:paf, 07/2023, 60d
		Clinical visits and diagnoses		:visits, 07/2023, 120d
		Labs and lab changes						:labs, after visits, 30d
		Clinical medication changes			:meds, after labs, 30d
		Rhythm/control strategies				:rhythm, after meds, 60d
		EPS data extraction							:eps, 01/2024, 90d
		NLP for notes										:nlp, after visits, 180d
	section Analysis
		Cross-sectional ECG							:clusters, after nsr, 30d
		ECG trajectories								:delta, after paf, 30d
		Cross-sectional clincal					:cross, after rhythm, 30d
		Clinical trajectories						:after tidy, 60d
	section Production
		CCTS/CBCD IRB										:done, irb, 04/2023, 30d
		ECG/AF Clusters 								:milestone, ecg, after delta, 7d
		Phenotype AF										:milestone, phenotype, after rhythm, 7d
```

