---
format: 
  docx: default
---

June 10, 2024  
AHA Scientific Sessions Early Career Awards  
Letter of Reference

To the Selection Committee and the Council on Epidemiology and Prevention: 

I am writing to offer my highest recommendation for Dr. Anish S. Shah, MD, MS, for the Elizabeth Barrett-Connor Research Award in Epidemiology and Prevention.

As a cardiovascular epidemiologist with over a decade of experience studying lifestyle, clinical, and genetic determinants of cardiovascular diseases through large prospective cohort studies, I have primarily focused on the epidemiology of atrial fibrillation (AF) and its complications. 
My research, funded by NHLBI and the American Heart Association, has included leadership roles in community-based cohorts such as the Atherosclerosis Risk in Communities (ARIC) study and the Multi-Ethnic Study of Atherosclerosis (MESA), focusing on the incidence, risk factors, and outcomes of AF. 
Additionally, I lead NHLBI-funded studies evaluating the comparative effectiveness of AF treatments and am involved in research assessing the impact of cardiovascular risk factors on cognitive decline, such as the ARIC Neurocognitive Study.

Over the past decade, I have provided informal mentoring through T32 training grants at the University of Minnesota and Emory University to numerous postdoctoral fellows, resulting in successful publications and grant funding. 
My commitment to mentoring junior clinical investigators is further evidenced by my recent NHLBI K24 award. 
My extensive publication, funding, mentoring record, and my expertise in the epidemiology of cardiac arrhythmias, uniquely qualify me to evaluate and support Anish's candidacy for this early career award.

I have known Anish since 2017, when he first approached me to study the effects of psychosocial stress in the ARIC study. 
At that time, he was just beginning his research career while completing his internal medicine residency. 
Anish successfully applied for and completed a manuscript proposal, resulting in a first-author publication in the Journal of the American Heart Association. 
Since then, he has published several additional manuscripts at the intersection of arrhythmias and epidemiology, demonstrating his strong foundation in epidemiologic methods and growing independence in performing complex statistical analyses.

Anish's commitment to research is further underscored by his NIH-TL1 grant in 2019 and his successful NIH-F32 grant in 2020, both of which I served as mentor and sponsor. 
I also helped to connect Anish with Dawood Darbar, who I know through overlapping interests in AF and genetics, his current sponsor where he is completing his physician-investigator track cardiology fellowship.
I will also mentor him for his K23 application after he completes his upcoming fellowship in clinical electrophysiology.
These accomplishments highlight Anish's exceptional ability to balance research productivity with clinical training.

Recently, Anish has focused on analyzing the social determinants of health as they relate to atrial fibrillation, particularly in patient-reported outcomes. 
He has collected quality-of-life data from nearly 1,000 patients and follow-up data on over 500 of them in a large observational study. 
The strength of his work lies in his focus on under-represented minorities, addressing a significant gap in the literature. 
His findings demonstrate how factors outside standard clinical care can affect AF symptom burden and emphasize the importance for clinicians to understand these contextual factors.

I am deeply impressed by Anish's findings and the growth he has shown in his research career. 
His work is both timely and important, and I believe he is an outstanding candidate for the Elizabeth Barrett-Connor Research Award. 
I expect him to continue growing and becoming a leader in the intersection of arrhythmias and epidemiology. 
I wholeheartedly support his application and believe he will make significant contributions to our field.


Sincerely,

Alvaro Alonso, MD, PhD  
Professor of Epidemiology  
Stephen D. Clements Jr. Chair in Cardiovascular Disease Prevention  
Rollins School of Public Health   
Emory University

