---
title: "Research Performance Progress Report: Response to Revision"
subtitle: "5F32HL154707-03: The Association of Autonomic Dysfunction with the Relationship between Depression and Coronary Disease"
format:
  pdf:
    papersize: letter
    mainfont: "Arial"
    fontsize: 11pt
---

\newpage

Kevin Purkiser and James Hennigan  
National Institutes of Health  
National Heart, Lung, and Blood Institute  
Epidemiology Branch  

Dear Drs. Purkiser and Hennigan,

Thank you for your response to my progress report. I apologize for the areas requiring revisions, and I appreciate the opportunity to do so, as my first time going through the NIH grant process. Below is the initial revision request, quoted:

> *1)  It’s not clear what has been accomplished in the past year toward your specific aims. The aims indicated in the competing application are to quantify the relationship between depressive symptoms and ANS dysfunction, and examine the relationship of obstructive CAD with ANS dysfunction and its potential dose response relationship. You indicate you have completed your Master’s thesis, participated in electrophysiology and other clinical training, analyzed mice models and stem cell models, and developed software. These are all great accomplishments, however, please clarify what you have done pursuant to the project’s specific aims.*
>
> *2)  You cite 3 publications, however, these were all published before the start of this project.  Table C.1. should include only publications directly arising from this project.  Please remove these publications from table C.1.*
>
> *3)  Enrollment: we acknowledge the continuing pandemic would cause enrollment to be lower than anticipated, however we are a little surprised there has been no enrollment at all, and the project is heading into its final year.  Please send us your current enrollment for this project in 3 months.*
>
> *4)  Some sections have been duplicated in the report (i.e. accomplishments, products, etc).  Please resend the report deleting these duplications.*


Anish S. Shah, MD, MS  
F32 Postdoctoral Fellow  
Division of Cardiology  
University of Illinois at Chicago  
(e) ashah282@uic.edu  
(c) 469-835-7606  
(p) 773-222-5619  

\newpage

# 1. Accomplishments and Specific Aims

In summary, my aims were to evaluate the relationship of stress, autononomic dysfunction, and structural/ischemic heart disease. Due to the limitations of enrollment over the past several years, my mentors and I  addressed this early on by delaying the start of the grant and diversifying the population we evaluated. We broadened the term depression to include other forms of psychological stress and evaluated additional cohorts. 
This was a natural extension of my work on neurocardiac pathophysiology that began under my previous TL1 grant. As quoted below:

>Aim 1. Quantify the relationship between depressive symptoms and ANS dysfunction. 
>
>Aim 2. Examine the relationship of obstructive CAD with ANS dysfunction and its potential dose-response relationship. 

For both of these aims, I needed additional background training in the measurement of autonomic physiology using electrocardiogram metrics and the evaluation of coronary artery disease through multiple imaging modalities. I used three cohorts: 1) Biobank Cohort (coronary angiography and heart rate variability via electrocardiogram patch), 2) Emory Twins Study (myocardial perfusion imaging and 24-hour Holter monitoring) and 3) Myocardial Ischemia and Mental Stress (mental stress challenge with both myocardial perfusion imaging and coronary angiography). This led to several accomplishments, both formal and informal, within my training plan.

*Biobank Cohort*

1. Utilizing the Master of Science in Clinical Research degree awarded from the TL-1 program, I successfully completed and the appropriate training needed to enroll patients for this project. I was able to consent and enroll over 50 individuals myself, and also trained part of our research team to enroll patients on my behalf. 
1. I learned how to organized and safely/confidentially store data using REDCap, creating an efficient standardized operating protocol for enrollment of patients. This is actively being used by our study staff to include more patients (usually several per week).
1. I developed computational and signal processing skills to be able to interpret ECG data collected directly from enrolled patients. This ECG data serves as a surrogate for autonomic function by measuring heart rate variability, and allows an understanding of dynamic changes in sympathovagal balance.

*Emory Twins Study*

1. To help evaluate changes in autonomic tone that may be circadian in nature, I wrote statistical software to analyze changes in heart rate variability by time of day through the _cosinor_ method of harmonic regressions. This is a work in progress but the first software package was released this year online.
1. I've initially analyzed this data and related it to the burden of depressive symptoms. This is a work-in-progress to become a manuscript hopefully in the next year.

*Myocardial Ischemia and Mental Stress*

1. I analyzed data involving acute psychological stress responses of heart rate and correlated this with cardiovascular mortality. This has subsequently turned into a first-author manuscript that is under revision with _Circulation_. 
1. This same cohort analysis (which showed a strong relationship between vagolysis and psychological stress), was accepted as an abstract at ACC 2023 of this year.

In summary, my findings pursuant to the specific aims are 1) association of depression and psychological stress with autonomic dysfunction and 2) association of autonomic dysfunction with cardiovascular mortality. These findings have led to software development, manuscript authorship, biostatistical analytical skills, and further learning in signal processing, which are all directly related to my overall training plan and specific aims.

\newpage

# 2. Publications and Products

The F32 was activated in December 2021. Since this time, there have been no manuscripts published, however I have drafted and submitted a manuscript that directly relates autonomic dysfunction under acute psychological stress with cardiovascular mortality, which is currently under revision in _Circulation_. This manuscript was also accepted in the form of an abstract to the American College of Cardiology 2023 Conference.

During this time, I have continued to work on patient enrollment to achieve adequate power (Biobank Cohort) to evaluate the dose-relationship between autonomic dysfunction and coronary artery disease.

\newpage

# 3. Enrollment

The enrollment documentation was submitted incorrectly. During the last year, we have seen an increase in the number of enrollments into the primary Biobank Cohort study.

The enrollment involves patients with suspected coronary artery disease that are undergoing routine/clinically-indicated coronary angiography. Continuous electrocardiogram data is being collected via ECG patch, that is subsequently being analyzed by myself. During their enrollment, the patients are being assessed for depressive symptom burden. 

**Enrollment Table:**

| Ethnicity       | Female | Male | Total |
| ---             | ---    | ---  | ---   |
| American Indian | 0      | 0    | 0     |
| Asian           | 1      | 11   | 12    |
| Black           | 9      | 14   | 23    |
| White           | 20     | 27   | 47    |
| Unknown/Mixed   | 4      | 2    | 6     |
| Total           | 34     | 54   | 88    |


