---
format: docx
---

# A. Cover Page

__5F32HL154707-03: The Association of Autonomic Dysfunction with the Relationship between Depression and Coronary Disease__  
Research Performance Progress Report  
October 3rd, 2022  

\newpage

# B. Accomplishments

## B1. What are the major goals of the project?

This project was an extension of my TL1 to understand and evaluate neurocardiac pathophysiology as a clinician-scientist. The major goals of the project were encapsulated within the specific aims:

1. Quantify the relationship between depressive symptoms and autonomic dysfunction
1. Examine the relationships of ischemic heart disease with autonomic dysfunction

Additionally, goals incorporated within the training plan included: expansion of biostatistical skills, signal processing techniques, and understanding of stress physiology

## B2. What was accomplished under these goals?

## B4.  What opportunities for training and professional development has the project provided?

## B5. How have the results been disseminated to communities of interest?

## B6. What do you plan to do during the next reporting period to accomplish the goals?

\newpage

# C. Products

## C5. Other products and resource sharing

\newpage

# F. Changes

## F2. Acutal or anticpated challenges or delays and actions or plans to resolve them


