---
format: docx
---

February 8, 2025

Paul J. Wang, MD  
Editor-in-Chief  
*Circulation: Arrhythmia and Electrophysiology*  

Dear Dr. Wang and the Editorial Board of *Circulation: Arrhythmia and Electrophysiology*,

We have keenly read the recent work published in *Circulation* on the extravascular implantable cardioverter/defbrillator (EV ICD), presented by Friedman et al. 2024 on behalf of the *Pivotal Study* investigators.

As an institution and as electrophysiologists, we have watched the astonishing progress made in terms of the development of new and innovative technology. 
With the excitement behind the EV ICD system, and the promising results of the *Pivotal Study*, we wanted to better understand how this device fit into the landscape of a quickly changing field. 
We examined the voluntary reports of device complications and compared that with the published data, understanding that the early-adoption is prone to challenge of novel learning curves, and does not portend the true safety of a mature technology.

We have attached a research letter supporting our findings, and believe that the audience of clinical cardiologists and electrophysiologists considering this technology will understand the breadth and depth of novel implementation techniques. 

With kind regards,

Anish S. Shah, MD, MS  
Electrophysiology Fellow  
University of Utah  

T. Jared Bunch, MD, FHRS  
Professor of Medicine  
University of Utah  


