---
format: docx
---

December 1, 2023
American Heart Association  
2023 Innovative Project Award  

Our research group, composed of translational cardiologists and cardiac electrophysiologists, propose an innovative approach to a causal, mechanistic step in the development of atrial fibrillation, and seek support for this high-risk, high-reward proposal. 

Atrial fibrillation (AF) remains the most common arrhythmia worldwide, afflicting over 1% of the population, but there is poor understanding of how the arrhythmia is triggered and maintained. 
Although left atrial dilatation and fibrosis are heavily coincident in later stages of AF in humans, triggered episodes of AF earlier in its course are poorly defined.
There is a strong association with the onset of AF episodes with negative emotions, with growing evidence supporting the role of the autonomic nervous system (ANS) in AF, such as sympathovagal imbalance occurring prior to the onset of an episode.
However, the electrophysiological manifestation of psychological stress remains mostly theoretical, with very few studies (if any) evaluating the sympathetic and vagal contributions to the onset of AF.

The atria are heavily innervated by autonomic ganglionic plexi, leading to the complex activity that regulates cardiac conductive properties. 
The key mechanism that we will explore is the intracardiac cross-talk between adrenergic (sympathetic) and cholinergic (vagal) neurons.
Adrenergic neurons release catecholamines that directly affect the myocardium, but indirectly as well through neuropeptide Y (NPY). 
NPY binds to cholinergic neurons through the Y2R receptor, inhibiting firing and leading to vagolytic effects on the myocardium.

We propose that in individuals with AF and structurally normal atria, episodes of AF will occur in the setting of vagolysis, and be blunted when vagal stimulation is provided. 
We hypothesize that 1) vagal stimulation protects against triggered episodes of AF in patients with structurally normal atria, and 2) blockade of vagolysis through vagal nerve stimulation with concomittant increased sympathetic activity protects from AF and improves myocardial conductive properties. 

We will recruit patients with structurally normal atria and paroxysmal AF who are undergoing electrophysiology study as part of indicated ablative therapy.
We will perform in-lab mental stress testing to assess changes in action potential duration (APD) using a monophasic action potential catheter. 
We will then assess the effect of both vagal nervous stimulation and atropine on APD modulation during mental stress provocation.

If, as we hypothesize, mental stress-induced changes in APD are reversed with vagal nerve stimulation, we will have not only established an innovative, causal mechanism in stress-induced arrhythmias, but identified a potential therapeutic pathway that changes the paradigm of the role of the ANS on AF.

We are thankful for the opportunity to discuss our proposal with the Review Committee, and welcome the opportunity to share any additional information as requested. 
