---
format: docx
---

October 3, 2022

F32 Awards Review Committee
National Heart, Lung, and Blood Institute, National Institutes of Health

Dear Review Committee,

It is our sincere pleasure to express our joint support for Dr. Anish S. Shah in his F32 award. We (Amit J. Shah, MD, MS with Emory University; Dawood Darbar, MBCHB, MD from University of Illinois at Chicago) have continued to co-mentor Dr. Shah throughout his clinical and research training, and can together discuss his tremendous progress.

He completed his TL1 grant in 2020, before starting his fellowship in clinical cardiology. He has completed two years of clinical training, and is now entering his protected research time. Subsequently, he plans to enter clinical electrophysiology fellowship, with the intent to become an academic clinical electrophysiologist. We expect that he will have obtained a K-award before he completes his clinical training.

Thus far, he has completed his coursework in epidemiology, biostatistics, and clinical research at Emory University, and maintains an active research presence on mental stress and cardiovascular physiology. He also now has joined a translational lab, where he is working on animal and cellular models of stress and the neurocardiac axis.

His epidemiology and computational-based work has already led to three first author papers, and his work on stress and arrhythmias will continue to expand during his training. 

We support his co-mentored training thus far and continue to believe he will develop into an outstanding translational clinical electrophysiologist.

Sincerely,

Dawood Darbar, MBChB, MD  
Chief, Division of Cardiology  
Co-Director, Medical Scientist Training Program (MSTP)  
Director, Center for Cardiovascular Research (CCVR)  
Professor of Medicine and Pharmacology  
University of Illinois at Chicago  
840 South Wood Street, Suite 928 M/C 715  
Chicago, IL 60612  
Office: 312.413.8870  
Fax: 312.413.2948  
Email: darbar@uic.edu  

Amit Shah, MD, MSCR  
Assistant Professor, Department of Epidemiology  
Assistant Professor, Department of Medicine, Division of Cardiology  
Staff Physician, Division of Cardiology, Atlanta VA Medical Center  
Emory University  
1518 Clifton Road NE, Room 3053  
Atlanta, GA 30322  
(T) 404-727-8712  
(C) 404-647-4351  
(F) 404-727-8737  
ajshah3@emory.edu  
