---
format: pdf
---

# A. Cover Page

__5F32HL154707-03: The Association of Autonomic Dysfunction with the Relationship between Depression and Coronary Disease__  
Research Performance Progress Report  
October 3rd, 2022  

\newpage

# B. Accomplishments

## B1. What are the major goals of the project?

This project was an extension of my TL1 to understand and evaluate neurocardiac pathophysiology as a clinician-scientist. The major goals of the project were encapsulated within the specific aims:

1. Quantify the relationship between depressive symptoms and autonomic dysfunction
1. Examine the relationships of ischemic heart disease with autonomic dysfunction

Additionally, goals incorporated within the training plan included: expansion of biostatistical skills, signal processing techniques, and understanding of stress physiology.

In terms of future planning, the end of the F32 is to help bridge me towards a K23 or K08 to move towards independence.

## B2. What was accomplished under these goals?

These goals allowed me to expand upon academic training, clinical training, and impactful scientific discoveries.

1. Master of Science degree: Able to complete a Master's Thesis and defend this using dedicated time from the F32 funding period. 
1. Clinical training: Completion of time as a clinical cardiology fellow, and movement towards electrophysiology training
1. Translational skills: Observation and development of basic science skills to allow for translational opportunities using mice models and IPSC models. 
1. Publications: "Alterations in heart rate variability are associated with abnormal myocardial perfusion" (PMID: 32024598) and "Association of Psychosocial Factors With Short‐Term Resting Heart Rate Variability: The Atherosclerosis Risk in Communities Study" (PMID: 33631952) as first author publications. Additionally, a key middle author publication in JAMA "Association of Mental Stress-Induced Myocardial Ischemia with Cardiovascular Events in Patients with Coronary Heart Disease" (PMID: 34751708).
1. Software development: During the learning of MATLAB, R, and other biostatistical techniques, I was able to generate and publish software on cosinor analyses, recurrent event analyses, and DAG-oriented modeling. These are actively maintained software packages that are furthering in development.

## B4.  What opportunities for training and professional development has the project provided?

Computational: The project has allowed me to develop an extensive technical skill base using programming techniques to learn biostatistics and signal processing. I have now become proficient in R and MATLAB, and routinely use this software on a daily basis. 

Clinical: I have entered and finished a majority of clinical cardiology training, and will expand my knowledge base as a researcher prior to entering clinical electrophysiology. I have made broad connections with federally funded investigators and continue to expand my pool of mentors.

## B5. How have the results been disseminated to communities of interest?

I have published within both JAHA, IJC, and JAMA, along with sending publications in abstract form to local and national conferences. 

## B6. What do you plan to do during the next reporting period to accomplish the goals?

I plan to complete data collection on patients being enrolled at my research center (Emory), and develop a translational model in animals to evaluate this further with my other mentors.

\newpage

# C. Products

## C5. Other products and resource sharing

I have published software on a public/open-source, peer-reviewed platform for statistically analyses (CRAN).

\newpage

# F. Changes

## F2. Acutal or anticpated challenges or delays and actions or plans to resolve them

COVID of course has made enrollment more challenging. In addition, the granularity of ECG-based data is difficult to ascertain based on context (e.g. time of day, activity level). I have planned to supplement this with data from device monitoring companies, and include a machine-learning approach to handle the large volume of data (e.g. using the MVP data at the VA systems).

# G. Special Reporting Requirements

## G2. Responsible Conduct of Research

During the reporting period, I have completed a Master of Science that included responsible research curriculum. Subsequently, I have continued training at institutional level on responsible research conduct as well as attending local seminars at the 1-3 month interval.
